Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "sched-affinity"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 4
    lv.memory = 2048
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 2048
  end

  # Isolate CPUs 1-3 from the scheduler, leaving only CPU 0 for regular apps.
  config.vm.provision "shell", inline: <<-SHELL
    grep -q 'isolcpus' /proc/cmdline || {
      sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*"/GRUB_CMDLINE_LINUX_DEFAULT="isolcpus=0"/' /etc/default/grub
      update-grub
      reboot
    }
  SHELL
end
